name: main

on:
  push:
    branches:
      - main

jobs:

  release:

    runs-on: ubuntu-latest
    
    env:
      DOCKER_BUILDKIT: 1
      image_name: makima_bot
      registry: cr.yandex/crpn1hg55doc8emgahe0

    steps:
    - uses: actions/checkout@v3

    - name: install jq
      run: sudo apt-get install jq

    - name: get app version
      id: app-version
      run: |
        echo "::set-output name=APP_VERSION::$(jq -r '.version' ./MakimaBot/application.config.json)"

    - name: build and run tests
      run: |
        docker build --target tests -t makima-tests .
        docker run makima-tests

    - name: build docker image
      run: |  
        docker build --target application -t makima-bot .

    - name: cr.yandex auth
      run: echo '${{ secrets.REGISTRY_KEY }}' | docker login -u json_key --password-stdin cr.yandex

    - name: check if image version exists
      run: |
        IMAGE_NAME="${{ env.registry }}/${{ env.image_name }}:${{ steps.app-version.outputs.APP_VERSION }}"
        if docker manifest inspect "$IMAGE_NAME" > /dev/null 2>&1; then
          echo "Error: Image version $IMAGE_NAME already exists! Update application version."
          exit 1
        fi

    - name: tag docker image
      run: |
        docker tag makima-bot ${{ env.registry }}/${{ env.image_name }}:${{ steps.app-version.outputs.APP_VERSION }}
    
    - name: docker push
      run: |
        docker push ${{ env.registry }}/${{ env.image_name }}:${{ steps.app-version.outputs.APP_VERSION }}
