name: pull request

on: pull_request

jobs:

  build:

    runs-on: ubuntu-latest
    
    env:
      DOCKER_BUILDKIT: 1

    steps:
    - uses: actions/checkout@v3

    - name: Install jq
      run: sudo apt-get install jq

    - name: path
      run: pwd

    - name: view
      run: ls -l

    - name: version
      run: cat ./MakimaBot/appversion.json

    - name: parse version
      run: |
        VERSION=$(jq -r '.version' ./MakimaBot/appversion.json)
        echo $VERSION
