name: pull request

on: pull_request

jobs:

  build:

    runs-on: ubuntu-latest
    
    env:
      DOCKER_BUILDKIT: 1
      image_name: makima_bot
      registry: cr.yandex/crpn1hg55doc8emgahe0
      app_config: ${{ secrets.APP_CONFIG }}

    steps:
    - uses: actions/checkout@v3

    - name: install jq
      run: sudo apt-get install jq

    - name: get app version
      run: |
        APP_VERSION=$(jq -r '.version' ./MakimaBot/appversion.json)
        echo $APP_VERSION
        echo "${{ env.app_config }}" > test.json
        cat test.json

    - name: build docker image
      run: |  
        docker build -t makima-bot ./MakimaBot/

    - name: tag docker image
      run: |
        docker tag makima-bot ${{ env.registry }}/${{ env.makima_bot }}:$APP_VERSION
    
    - name: docker push
      run: |
        docker push ${{ env.registry }}/${{ env.makima_bot }}:$APP_VERSION
