name: pull request

on: pull_request

jobs:

  build:

    runs-on: ubuntu-latest
    
    env:
      DOCKER_BUILDKIT: 1

    steps:
    - uses: actions/checkout@v3

    - name: path
      run: pwd

    - name: view
      run: ls -l

    - name: version
      run: cat ./appversion.json
